// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Omphalos.Repository;

#nullable disable

namespace Omphalos.Repository.Migrations
{
    [DbContext(typeof(OmphalosDbContext))]
    partial class OmphalosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Omphalos.Domain.Entities.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Alignment")
                        .HasColumnType("text");

                    b.Property<string>("Class")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Flaw")
                        .HasColumnType("text");

                    b.Property<string>("Inventory")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PersonalityTraits")
                        .HasColumnType("text");

                    b.Property<string>("PortraitBase64")
                        .HasColumnType("text");

                    b.Property<double>("PortraitPanX")
                        .HasColumnType("double precision");

                    b.Property<double>("PortraitPanY")
                        .HasColumnType("double precision");

                    b.Property<string>("QuestHooks")
                        .HasColumnType("text");

                    b.Property<string>("Race")
                        .HasColumnType("text");

                    b.Property<string>("Relationships")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Omphalos.Domain.Entities.Encounter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("Omphalos.Domain.Entities.GameSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<long>("DateCreated")
                        .HasColumnType("bigint");

                    b.Property<long>("DateModified")
                        .HasColumnType("bigint");

                    b.Property<JsonDocument>("SessionLog")
                        .HasColumnType("jsonb");

                    b.Property<string>("SessionNotes")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("Omphalos.Domain.Entities.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageBase64")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Omphalos.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Omphalos.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("GeminiApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Omphalos.Domain.Entities.Character", b =>
                {
                    b.HasOne("Omphalos.Domain.Entities.GameSession", "Session")
                        .WithMany("Characters")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Omphalos.Domain.Entities.Encounter", b =>
                {
                    b.HasOne("Omphalos.Domain.Entities.GameSession", "Session")
                        .WithMany("Encounters")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Omphalos.Domain.Entities.GameSession", b =>
                {
                    b.HasOne("Omphalos.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Omphalos.Domain.Entities.SessionMetadata", "Metadata", b1 =>
                        {
                            b1.Property<string>("GameSessionId")
                                .HasColumnType("text");

                            b1.Property<string>("DateTime")
                                .HasColumnType("text")
                                .HasColumnName("meta_date_time");

                            b1.Property<string>("Location")
                                .HasColumnType("text")
                                .HasColumnName("meta_location");

                            b1.Property<string>("NextSessionHooks")
                                .HasColumnType("text")
                                .HasColumnName("meta_next_session_hooks");

                            b1.Property<string>("NpcsMet")
                                .HasColumnType("text")
                                .HasColumnName("meta_npcs_met");

                            b1.Property<string>("PartyLevelChange")
                                .HasColumnType("text")
                                .HasColumnName("meta_party_level_change");

                            b1.Property<string>("PlotPoints")
                                .HasColumnType("text")
                                .HasColumnName("meta_plot_points");

                            b1.Property<string>("TreasureAcquired")
                                .HasColumnType("text")
                                .HasColumnName("meta_treasure_acquired");

                            b1.Property<string>("Weather")
                                .HasColumnType("text")
                                .HasColumnName("meta_weather");

                            b1.HasKey("GameSessionId");

                            b1.ToTable("GameSessions");

                            b1.WithOwner()
                                .HasForeignKey("GameSessionId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omphalos.Domain.Entities.Location", b =>
                {
                    b.HasOne("Omphalos.Domain.Entities.GameSession", "Session")
                        .WithMany("Locations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Omphalos.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("Omphalos.Domain.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("Omphalos.Domain.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Omphalos.Domain.Entities.GameSession", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Encounters");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Omphalos.Domain.Entities.User", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
